version: 2

sources:
  - name: library
    schema: main
    tables: 
      - name: books_factual
        columns: 
          - name: book_id
            data_tests: 
              - unique
              - not_null
          - name: books_fictional
          